# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-16 23:27
from __future__ import unicode_literals

import apps.common.fields
import apps.common.helpers.media_filename_hash
import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True, verbose_name='کاربر')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('role', models.CharField(max_length=50, verbose_name='role', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='updated date')),
                ('last_login_date', models.DateTimeField(blank=True, null=True, verbose_name='last login date')),
            ],
            options={
                'verbose_name': 'user_session',
                'db_table': 'user_session',
            },
        ),
    ]
