POINT_EMTIAZ = 1
OTHER_COUNTY_POINT = 1
OTHER_PROVINCE_POINT = 2
OTHER_NATIONALITY_POINT = 3
FIRST_PERSON_RATING = 2

MINIMUM_PERCENTAGE_POINT = 20
COUNT_RATE_ACTIVITIES = 50
LICKERT = 10
QUALITY_INDEX = 2

LOGARITHMIC_BASIS = 2  # 1.67

ALPHA_IN_EVENT = 2
BETA_WITH_EVENT = 1

IN_EVENT_NUMBER = 5
WITH_EVENT_NUMBER = 10

LIST_ACTION = [
    "category",
    "department",
    "daily_activity",
    "weekly_activity",
    "best_student",
]
